# Requires:
# a2enmod ssl proxy proxy_http headers rewrite

<VirtualHost *:80>
    ServerName example.hostname

    # Redirect all HTTP to HTTPS with 308
    RewriteEngine On
    RewriteRule ^ https://%{HTTP_HOST}%{REQUEST_URI} [R=308,L]
</VirtualHost>

<VirtualHost *:443>
    ServerName example.hostname

    SSLEngine on
    SSLCertificateFile      /path/to/certificate.pem
    SSLCertificateKeyFile   /path/to/key.pem

    SSLProtocol             TLSv1.2 TLSv1.3
    SSLCipherSuite          HIGH:!aNULL:!MD5

    # Proxy settings
    ProxyPreserveHost On

    RequestHeader set X-Forwarded-Host "%{Host}e"
    RequestHeader set X-Forwarded-Proto "https"
    RequestHeader set X-Real-IP "%{REMOTE_ADDR}e"
    RequestHeader add X-Forwarded-For "%{REMOTE_ADDR}e"

    ProxyPass        / http://localhost:8080/
    ProxyPassReverse / http://localhost:8080/
</VirtualHost>