name: release

on:
  release:
    types: [published]

permissions:
  contents: write   # needed to upload assets to the release
  packages: write   # needed to push docker images to ghcr.io

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (full history for tags)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true

      - name: Determine version from tag
        id: ver
        run: |
          RAW_TAG="${{ github.event.release.tag_name }}"
          # strip a leading 'v' if present (v1.2.3 -> 1.2.3)
          STRIPPED="${RAW_TAG#v}"
          echo "version=$STRIPPED" >> "$GITHUB_OUTPUT"

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build release artifacts
        env:
          VERSION: ${{ steps.ver.outputs.version }}
        run: |
          # Ensure artifact dir is fresh
          rm -rf dist
          mkdir -p dist
          # Your Makefile's `release` should populate ./dist/
          make release VERSION="$VERSION"
          echo "Artifacts:"
          ls -l dist || true

      - name: Upload artifacts to the GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/**
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
